version: "3"

services:
  db:
    container_name: sdjs-mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=sdjs-speaker-api
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
